name: Feature Request
description: Request a new feature or enhancement.
title: "[Feature]: "
labels: ["enhancement"]
projects: ["bohning/usdb_syncer"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: checkbox
    id: confirmed-searched-issues
    attributes:
      label: I searched existing issues for similar feature requests.
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature you would like to see
      description: Provide as much detail as possible.
    validations:
      required: true
